name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Swift version
        uses: fwal/setup-swift@v1

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_26.1.app && /usr/bin/xcodebuild -version
      
      - name: Build for macOS
        uses: mxcl/xcodebuild@v3
        with:
          platform: macOS
          xcode: ^26.1
          scheme: Fluxo
          action: build

      - name: Runing tests for macOS
        uses: mxcl/xcodebuild@v3
        with:
          platform: macOS
          xcode: ^26.1
          scheme: Fluxo
          action: test
